# YOUR NAME OR TITLE OF YOUR SITE
name: DJ Arka (Marius)

# YOUR BRAND/PERSONAL TAGLINE
tagline: Howdy, I'm DJ Arka (Marius). I'm a passionate Tech Lover from Romania, apart from that I'm a Graphic Designer and an OpenSource enthusiast Inspired by Imagination.

# YOUR/BRAND IMAGE URL
Image_URL: https://i.imgur.com/lqpFhI2.jpg

# CHANGE THE BACKGROUND IMAGE OF THE WEBSITE BY JUST ADDING THE IMAGE URL
Cover_Image: https://source.unsplash.com/random

# SOCIAL MEDIA
links:

  # IF YOU DON'T WANT TO USE ANY OF THE FOLLOWING, JUST LEAVE THE URL BLANK
    
    # FACEBOOK

    # INSTAGRAM
  - Name: Instagram
    URL: https://www.instagram.com
    Username: dj.arka
    Color: '#DD2A7B'
    Icon-Class: fab fa-instagram

    # TWITTER
  - Name: Twitter
    URL: https://twitter.com
    Username: DjArkaa
    Color: '#1DA1F2'
    Icon-Class: fab fa-twitter

    # CLUBHOUSE
  - Name: Clubhouse
    URL: https://www.clubhouse.com
    Username: '@djarkaa'
    Color: '#f1c40f'
    Icon-Class: fas fa-hand-paper -mt-0.5
    
    # LINKEDIN
  - Name: LinkedIn
    URL: https://www.linkedin.com/in
    Username: DJ Arka
    Color: '#2867B2'
    Icon-Class: fab fa-linkedin-in

    # YOUTUBE
  - Name: YouTube
    URL: https://www.youtube.com/channel
    Username: UC64cK3VjGLHOAp7ROviT_BQ
    Color: '#ff0000'
    Icon-Class: fab fa-youtube

    # GITHUB
  - Name: GitHub
    URL: http://github.com
    Username: DjArkaa
    Color: '#6e5494'
    Icon-Class: fab fa-github

    # EMAIL
  - Name: Email
    URL: 'admin@djarka.studio'
    Icon-Class: fas fa-envelope
    Color: '#e17055'
    Text_Color: '#ffffff'

    # TWITCH
  - Name: Twitch
    URL: 'https://twitch.tv'
    Username: djarkaaa
    Icon-Class: fab fa-twitch
    Color: '#9147fe'
    Text_Color: '#ffffff'

  #   # WHATSAPP
  # - Name: WhatsApp
  #   URL: https://wa.me
  #   Username: '+1123456789'
  #   Color: '#25d366'
  #   Icon-Class: fab fa-whatsapp

    # SNAPCHAT
  - Name: Snapchat
    URL: https://www.snapchat.com/add
    Username: 'gica_hussein20'
    Color: '#FFFC00'
    Text_Color: '#000000'
    Icon-Class: fab fa-snapchat-ghost

  #   # DISCORD
  # - Name: Discord
  #   URL: 'https://discord.gg'
  #   Username: 
  #   Icon-Class: fab fa-discord
  #   Color: '#5865F2'
  #   Text_Color: '#ffffff'

    # PINTEREST
  - Name: Pinterest
    URL: https://pinterest.com
    Username: 'DjArkaa'
    Color: '#E60023'
    Icon-Class: fab fa-pinterest

  #   # DRIBBBLE
  # - Name: Dribbble
  #   URL: https://dribbble.com
  #   Username: 
  #   Color: '#ea4c89'
  #   Icon-Class: fab fa-dribbble

    # SPOTIFY
  - Name: Spotify
    URL: http://open.spotify.com/user
    Username: DjArka
    Color: '#1DB954'
    Icon-Class: fab fa-spotify

    # SOUNDCLOUD
  - Name: SoundCloud
    URL: https://www.soundcloud.com
    Username: DjArka 
    Color: '#FE5000'
    Icon-Class: fab fa-soundcloud

  #    # TIKTOK
   - Name: TikTok
     URL: https://www.tiktok.com
     Username: djarkaa
     Color: '#FE2C55'
     Icon-Class: fab fa-tiktok

  #   # TUMBLR
  # - Name: Tumblr
  #   URL: https://www.tumblr.com
  #   Username: 
  #   Color: '#35465c'
  #   Icon-Class: fab fa-tumblr

# YOU CAN REMOVE FOOTER COMPLETELY BY SIMPLY REMOVING EITHER THE YES OR REMOVING THE FOOTER STATEMENT BELOW COMPLETELY
footer: 'Yes'

# STOP EDITING HERE ---------- YOU'VE REACHED THE END OF THE CONFIGURATION

# Compress
compress_html:
  clippings: all

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Icon

# Base URL
# baseurl: /links

# Default Markdown Engine
markdown: kramdown
